
logging:
  level:
    com.example.numble.timedeal : debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.hibernate.SQL : debug

spring:
  datasource:
    url: ${DATASOURCE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    properties:
      hibernate.show-sql: true
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100

